### PR TITLE
API to support waterfall clustering in LAA

### PR DESCRIPTION
**Pull request by nlhepler**

### CODE REVIEW

**Comment by evolvedmicrobe** [comment]
No idea what is going on with this one, mind giving me a brief description (just want to stay in the loop)

**Comment by dalexander** [comment]
Nigel: the "waterfall" clustering refers to a project to reduce memory consumption in the coarse-clustering step of LAA by doing the clustering incrementally instead of building an enormous matrix at the outset.

I can't speak to why this change was necessary.

**Comment by dalexander** [comment]
Ideally this change would have been in `pbsparse`, but my understanding is that we are bundling a piece of `pbsparse` with `pbccs`.  Only Lance knows why.

**Comment by nlhepler** [comment]
Well for one, this version of FindSeeds isn't used here, it's used when we want to compare to sequences in a set (with sequences from the same set--here qIdx is used to skip over self--by making it optional we let an outsider compare themselves to the set as well).

**Pull request merged**
