### PR TITLE
Add tool contract of --noPolish to task_pbccs_ccs

### PR DESCRIPTION
**Pull request by ylipacbio**
bug 30718

### CODE REVIEW

**Comment by dalexander** [comment]
ok, I was not aware of this.  the ini file in S3.0 is going to need to be updated

**Comment by nlhepler** [comment]
@ylipacbio took care of it, @dalexander

**Comment by ylipacbio** [comment]
I only updated mainline ini, but didn't update S3.0 ini, because bug 30718 is 3.0.4, not 3.0.3

**Comment by dalexander** [comment]
ok great

**Pull request merged**
