### PR TITLE
enable complete barcode support, test data pending

### PR DESCRIPTION
**Pull request by nlhepler**
clang-format once again reordered my headers, but otherwise this enable propagation of:
1) ReadGroupInfo BarcodeData
2) "bc" and "bq" tags for barcode assignments and barcode quality, respectively
3) bailing out if the data doesn't hold to the contract of same calls and quality for each subread from a ZMW

### CODE REVIEW

**Comment by evolvedmicrobe** [comment]
Looks good, this will also require an update to README.md

**Comment by nlhepler** [comment]
Let me update the PR with a commit for the CHANGELOG and the README

**Comment by nlhepler** [comment]
Now with documentation!

**Comment by nlhepler** [comment]
@evolvedmicrobe waiting your review

**Comment by evolvedmicrobe** [comment]
Looks good to me, I probably would have mentioned the field numbering changes in the readme, but they are on different commits so I think it's okay.

**Pull request merged**
