### PR TITLE
more pbsmrtpipe integration

### PR DESCRIPTION
**Pull request by natechols**
The most important part (which I forgot in the commit messages) is using ZMW ranges for chunked datasets.

### CODE REVIEW

**Comment by natechols** [comment]
Hold on, I may need that index file generation after all...

**Comment by evolvedmicrobe** [comment]
Can we avoid outputting that index?  By restricting the number of interdependencies and separating functionally distinct components software is much easier to write, read, debug and maintain.

**Comment by natechols** [comment]
Yeah, we really need a central, general solution for this problem.

**Comment by natechols** [comment]
And I think I figured out the general solution, using a decorator defined by pbcommnad

**Comment by evolvedmicrobe** [comment]
should I go ahead and merge then?

**Comment by natechols** [comment]
yes, the ZMW range is critical

**Pull request merged**
